import type { Metadata } from "next";
import { ErrorBoundary } from "next/dist/client/components/error-boundary";
import { Suspense } from "react";
import { MarkAllNotificationsReadButton } from "@/components/edms/notification-actions";
import { ErrorFallback } from "@/components/error-fallback";
import { NotificationsTable } from "@/components/notifications-table";
import { ScrollableContent } from "@/components/scrollable-content";
import { getEdmsNotificationFeed } from "@/lib/edms/notification-feed";
import { getRequiredDashboardSessionUser } from "@/lib/edms/session";

export const metadata: Metadata = {
  title: "Activities | Quadra EDMS",
};

export default async function NotificationsPage() {
  const sessionUser = await getRequiredDashboardSessionUser();

  return (
    <ScrollableContent>
      <ErrorBoundary errorComponent={ErrorFallback}>
        <Suspense
          fallback={
            <div className="text-sm text-muted-foreground">
              Loading notifications...
            </div>
          }
        >
          <NotificationsContent sessionUser={sessionUser} />
        </Suspense>
      </ErrorBoundary>
    </ScrollableContent>
  );
}

async function NotificationsContent({ sessionUser }: { sessionUser: any }) {
  const notifications = await getEdmsNotificationFeed(sessionUser, 50);

  return (
    <div className="space-y-6 px-8 pt-8">
      <section className="flex flex-col gap-4 md:flex-row md:items-end md:justify-between">
        <div className="max-w-3xl space-y-3">
          <div className="space-y-2">
            <h1 className="text-3xl font-semibold tracking-tight md:text-4xl">
              Activities
            </h1>
            <p className="text-sm leading-6 text-muted-foreground md:text-base">
              Review requests, transmittals, and approval decisions generated by
              the EDMS workflow.
            </p>
          </div>
        </div>
        <MarkAllNotificationsReadButton
          disabled={notifications.every((item) => item.isRead)}
        />
      </section>

      <section className="space-y-4">
        <div className="space-y-1">
          <h2 className="text-xl font-semibold tracking-tight">
            All notifications
          </h2>
          <p className="text-sm text-muted-foreground">
            Workflow activity and alerts rendered in the shared table layout.
          </p>
        </div>

        {notifications.length === 0 ? (
          <div className="rounded-md border border-dashed p-6 text-sm text-muted-foreground">
            No notifications available.
          </div>
        ) : (
          <NotificationsTable notifications={notifications} />
        )}
      </section>
    </div>
  );
}
