import { vegetableProducts } from "@/data/vegetable-products";
import { localizedValue } from "@/lib/store-locale";
import {
  defaultRoshalExtendedPages,
  defaultRoshalExtendedSections,
} from "@/lib/store-marketing-defaults";
import type {
  RoshalMarketingPage,
  RoshalMarketingSection,
  RoshalPaymentSettings,
  RoshalProduct,
  RoshalSiteSettings,
} from "@/lib/store-types";

const nowId = "default";

export const defaultRoshalSiteSettings: RoshalSiteSettings = {
  id: nowId,
  brandName: "Roshal Organic",
  tagline: localizedValue("খাঁটি স্বাদের আসল ঠিকানা", "The real home of pure taste"),
  contactPhone: "01805-767300",
  contactEmail: "roshalorganic@gmail.com",
  whatsappPhone: "01805-767300",
  facebookUrl: "https://www.facebook.com/roshalorganic",
  address: localizedValue(
    "মোহাম্মদপুর, ঢাকা, বাংলাদেশ",
    "Mohammadpur, Dhaka, Bangladesh",
  ),
  heroLayout: "split",
  cardStyle: "soft",
  sectionSpacing: "comfortable",
  primaryCtaHref: "/products",
  primaryCtaLabel: localizedValue("এখনই অর্ডার করুন", "Order now"),
  deliveryZones: [
    {
      id: "delivery-inside-dhaka",
      label: localizedValue("ঢাকার ভিতরে", "Inside Dhaka"),
      fee: 60,
      cityPatterns: ["dhaka", "ঢাকা"],
      postalCodes: [],
      addressKeywords: ["dhaka", "ঢাকা", "uttara", "banani", "mirpur"],
      isEnabled: true,
      isDefault: true,
      sortOrder: 0,
    },
    {
      id: "delivery-nearby",
      label: localizedValue("ঢাকার আশেপাশে", "Nearby districts"),
      fee: 100,
      cityPatterns: [
        "gazipur",
        "নারায়ণগঞ্জ",
        "narayanganj",
        "savar",
        "keraniganj",
      ],
      postalCodes: [],
      addressKeywords: ["gazipur", "narayanganj", "savar", "keraniganj"],
      isEnabled: true,
      isDefault: false,
      sortOrder: 1,
    },
    {
      id: "delivery-nationwide",
      label: localizedValue("সারা বাংলাদেশ", "Nationwide"),
      fee: 130,
      cityPatterns: [],
      postalCodes: [],
      addressKeywords: [],
      isEnabled: true,
      isDefault: false,
      sortOrder: 2,
    },
  ],
};

export const defaultRoshalPages: RoshalMarketingPage[] = [
  {
    id: "page-home",
    slug: "home",
    navigationLabel: localizedValue("হোম", "Home"),
    title: localizedValue("Roshal Organic", "Roshal Organic"),
    description: localizedValue(
      "প্রাকৃতিক ও স্বাস্থ্যসম্মত খাদ্যের নির্ভরযোগ্য ঘর।",
      "A trusted home for natural and healthy foods.",
    ),
    heroImage: "/special-offer.jpg",
    status: "published",
    showInNavigation: true,
  },
  {
    id: "page-about",
    slug: "about",
    navigationLabel: localizedValue("আমাদের সম্পর্কে", "About"),
    title: localizedValue("Roshal Organic – পরিচিতি", "About Roshal Organic"),
    description: localizedValue(
      "আমাদের লক্ষ্য, প্রতিশ্রুতি ও খাঁটি খাদ্যের গল্প।",
      "Our mission, promises, and the story behind our pure food brand.",
    ),
    heroImage: "/brand-story.jpg",
    status: "published",
    showInNavigation: true,
  },
  {
    id: "page-contact",
    slug: "contact",
    navigationLabel: localizedValue("যোগাযোগ", "Contact"),
    title: localizedValue("যোগাযোগ করুন", "Get in touch"),
    description: localizedValue(
      "অর্ডার, পাইকারি জিজ্ঞাসা বা সহায়তার জন্য যোগাযোগ করুন।",
      "Contact us for orders, wholesale inquiries, or support.",
    ),
    heroImage: "/newsletter.jpg",
    status: "published",
    showInNavigation: true,
  },
  ...defaultRoshalExtendedPages,
];

const defaultRoshalCorePageEnhancements: RoshalMarketingSection[] = [
  {
    id: "section-about-sourcing-story",
    pageId: "page-about",
    sectionKey: "sourcing-story",
    type: "story",
    sortOrder: 2,
    layout: "split",
    variant: "muted",
    isEnabled: true,
    eyebrow: localizedValue("সংগ্রহের গল্প", "How we source"),
    title: localizedValue(
      "খামার, মৌচাক ও স্থানীয় উৎপাদক থেকে যত্নে সংগ্রহ",
      "Carefully sourced from farms, beekeepers, and local producers",
    ),
    body: localizedValue(
      "Roshal Organic পণ্যের মূল শক্তি হলো নির্ভরযোগ্য উৎস। মৌসুমি ফল, খাঁটি মধু, ঘি, তেল এবং রান্নাঘরের প্রয়োজনীয় পণ্য আমরা এমন অংশীদারদের কাছ থেকে সংগ্রহ করি যাদের সঙ্গে মান, সততা এবং নিয়মিত যোগাযোগ বজায় রাখা যায়।",
      "Roshal Organic is built on dependable sourcing. From seasonal fruits and pure honey to ghee, oils, and kitchen essentials, we work with partners we can trust for quality, consistency, and honest communication.",
    ),
    ctaLabel: localizedValue("Company Information", "Company Information"),
    ctaHref: "/company-information",
    imageUrl: "/farming.jpg",
    items: [],
    styles: {
      emphasis: "editorial",
    },
  },
  {
    id: "section-about-quality-standards",
    pageId: "page-about",
    sectionKey: "quality-standards",
    type: "feature-grid",
    sortOrder: 3,
    layout: "grid",
    variant: "default",
    isEnabled: true,
    eyebrow: localizedValue("মান নিয়ন্ত্রণ", "Quality standards"),
    title: localizedValue(
      "আমরা যে কারণে পণ্যের মানে কঠোর",
      "Why we stay strict about product quality",
    ),
    body: localizedValue(
      "প্রতিটি পণ্য গ্রাহকের টেবিলে পৌঁছানোর আগে কয়েকটি বাস্তব যাচাইয়ের ভেতর দিয়ে যায়।",
      "Every product goes through a few practical checkpoints before it reaches a customer table.",
    ),
    ctaLabel: localizedValue("যোগাযোগ করুন", "Contact us"),
    ctaHref: "/contact",
    imageUrl: "",
    items: [
      {
        title: localizedValue("ট্রেসেবল সোর্সিং", "Traceable sourcing"),
        body: localizedValue(
          "পণ্যের উৎস, উৎপাদক এবং মৌসুমি প্রেক্ষাপট জানা থাকে।",
          "We keep the source, producer, and seasonal context visible wherever possible.",
        ),
      },
      {
        title: localizedValue("সতর্ক বাছাই", "Careful selection"),
        body: localizedValue(
          "ক্যাটালগে তোলার আগে গুণগত মান, ব্যবহারযোগ্যতা এবং গ্রাহক প্রত্যাশা বিবেচনা করা হয়।",
          "Quality, usability, and customer expectations are reviewed before a product is listed.",
        ),
      },
      {
        title: localizedValue("পরিষ্কার প্যাকেজিং", "Clean packaging"),
        body: localizedValue(
          "পণ্য, পরিমাণ এবং ডেলিভারি উপযোগিতা মিলিয়ে প্যাকেজিং প্রস্তুত করা হয়।",
          "Packaging is prepared to match the product, quantity, and delivery conditions.",
        ),
      },
      {
        title: localizedValue("দ্রুত সাপোর্ট", "Responsive support"),
        body: localizedValue(
          "অর্ডার, পেমেন্ট, ডেলিভারি বা রিটার্ন বিষয়ে দ্রুত ফলো-আপ দেওয়া হয়।",
          "Fast follow-up is available for orders, payments, delivery, or returns.",
        ),
      },
    ],
    styles: {
      columns: "2",
    },
  },
  {
    id: "section-contact-help-topics",
    pageId: "page-contact",
    sectionKey: "contact-help-topics",
    type: "feature-grid",
    sortOrder: 2,
    layout: "grid",
    variant: "default",
    isEnabled: true,
    eyebrow: localizedValue("সাহায্যের ধরণ", "Ways we can help"),
    title: localizedValue(
      "কোন বিষয়ে যোগাযোগ করবেন",
      "What you can contact us about",
    ),
    body: localizedValue(
      "একই যোগাযোগ পেজ থেকে retail order, wholesale, delivery follow-up এবং custom sourcing request হ্যান্ডেল করা যায়।",
      "The same contact page can route retail orders, wholesale requests, delivery follow-up, and custom sourcing inquiries.",
    ),
    ctaLabel: localizedValue("সাপোর্ট সেন্টার", "Support Center"),
    ctaHref: "/support-center",
    imageUrl: "",
    items: [
      {
        title: localizedValue("রিটেইল অর্ডার", "Retail orders"),
        body: localizedValue(
          "পণ্য নির্বাচন, অর্ডার প্লেসমেন্ট, পরিবর্তন বা কনফার্মেশন সংক্রান্ত প্রশ্নের জন্য।",
          "For product selection, order placement, changes, or order confirmation questions.",
        ),
      },
      {
        title: localizedValue("পাইকারি ও B2B", "Wholesale and B2B"),
        body: localizedValue(
          "দোকান, রিসেলার, কর্পোরেট gifting বা পুনরাবৃত্ত bulk requirement-এর জন্য।",
          "For retailers, resellers, corporate gifting, or repeat bulk requirements.",
        ),
      },
      {
        title: localizedValue("ডেলিভারি ফলো-আপ", "Delivery follow-up"),
        body: localizedValue(
          "ডেলিভারি এলাকা, সময়, status update বা receiving issue-এর জন্য।",
          "For delivery-area, timing, status-update, or receiving-condition questions.",
        ),
      },
      {
        title: localizedValue("বিশেষ সংগ্রহ অনুরোধ", "Custom sourcing"),
        body: localizedValue(
          "মৌসুমি, limited-stock বা ক্যাটালগের বাইরে sourcing request জানাতে পারবেন।",
          "Use this route to ask about seasonal, limited-stock, or off-catalog sourcing requests.",
        ),
      },
    ],
    styles: {
      columns: "2",
    },
  },
  {
    id: "section-contact-service-promise",
    pageId: "page-contact",
    sectionKey: "service-promise",
    type: "story",
    sortOrder: 0,
    layout: "split",
    variant: "muted",
    isEnabled: true,
    eyebrow: localizedValue("সার্ভিস স্ট্যান্ডার্ড", "Service standards"),
    title: localizedValue(
      "দ্রুত উত্তর, পরিষ্কার নির্দেশনা, এবং মানুষের মতো সাপোর্ট",
      "Fast replies, clear guidance, and human support",
    ),
    body: localizedValue(
      "Roshal Organic-এর যোগাযোগ ফ্লো এমনভাবে সাজানো যে অর্ডার, পেমেন্ট বা ডেলিভারি-সংক্রান্ত প্রশ্নে গ্রাহককে বারবার একই তথ্য দিতে না হয়। প্রয়োজন হলে support team অর্ডার রিভিউ, payment verification এবং delivery coordination একসঙ্গে দেখে।",
      "Roshal Organic is structured so customers do not have to repeat themselves across order, payment, or delivery conversations. When needed, the support team can coordinate order review, payment verification, and delivery updates together.",
    ),
    ctaLabel: localizedValue("অর্ডার ট্র্যাক করুন", "Track your order"),
    ctaHref: "/orders",
    imageUrl: "/packaging.jpg",
    items: [],
    styles: {
      emphasis: "balanced",
    },
  },
  {
    id: "section-contact-response-commitments",
    pageId: "page-contact",
    sectionKey: "response-commitments",
    type: "contact-cards",
    sortOrder: 3,
    layout: "grid",
    variant: "soft",
    isEnabled: true,
    eyebrow: localizedValue("দ্রুত পথ", "Quick routes"),
    title: localizedValue(
      "যে যোগাযোগ পথটি আপনার জন্য সবচেয়ে উপযোগী",
      "Choose the contact route that fits your need",
    ),
    body: localizedValue(
      "প্রয়োজন অনুযায়ী sales, support, tracking বা WhatsApp conversation আলাদা করে দেখাতে পারবেন।",
      "Separate sales, support, tracking, and WhatsApp routes so customers can pick the right path immediately.",
    ),
    ctaLabel: localizedValue("Payment Guide", "Payment Guide"),
    ctaHref: "/payment",
    imageUrl: "",
    items: [
      {
        label: localizedValue("Order support", "Order support"),
        title: localizedValue("+880 1719-403627", "+880 1719-403627"),
        body: localizedValue(
          "অর্ডার কনফার্মেশন, edit, cancellation বা delivery follow-up-এর জন্য।",
          "For order confirmation, edits, cancellation, or delivery follow-up.",
        ),
        href: "tel:+8801805767300",
      },
      {
        label: localizedValue("WhatsApp", "WhatsApp"),
        title: localizedValue("Live chat support", "Live chat support"),
        body: localizedValue(
          "দ্রুত screenshot, payment proof বা short support message শেয়ার করার জন্য।",
          "Best for sharing screenshots, payment proof, or a quick support message.",
        ),
        href: "https://wa.me/8801805767300",
      },
      {
        label: localizedValue("Wholesale", "Wholesale"),
        title: localizedValue(
          "info@roshalorganic.com",
          "info@roshalorganic.com",
        ),
        body: localizedValue(
          "পাইকারি, retail partnership, gifting বা repeat supply discussion-এর জন্য।",
          "For wholesale, retail partnership, gifting, or repeat supply discussions.",
        ),
        href: "mailto:info@roshalorganic.com",
      },
      {
        label: localizedValue("Order Tracking", "Order Tracking"),
        title: localizedValue("নিজে status দেখুন", "Check status yourself"),
        body: localizedValue(
          "লগইন করা গ্রাহক profile ও order history থেকে live status দেখতে পারবেন।",
          "Signed-in customers can check live status from profile and order history.",
        ),
        href: "/orders",
      },
    ],
    styles: {
      columns: "2",
    },
  },
];

export const defaultRoshalSections: RoshalMarketingSection[] = [
  {
    id: "section-home-hero",
    pageId: "page-home",
    sectionKey: "hero",
    type: "hero",
    sortOrder: 0,
    layout: "split",
    variant: "accent",
    isEnabled: true,
    eyebrow: localizedValue("Roshal Organic", "Roshal Organic"),
    title: localizedValue(
      "১০০% খাঁটি, কেমিক্যালমুক্ত ও বিশ্বাসযোগ্য খাবার",
      "100% pure, chemical-free, trustworthy food",
    ),
    body: localizedValue(
      "Roshal Organic মানুষের ঘরে পৌঁছে দেয় মধু, ঘি, গুড়, ফল, তেল ও আরও অনেক প্রাকৃতিক খাদ্য। আমাদের প্রতিটি পণ্য সরাসরি কৃষক ও প্রাকৃতিক উৎস থেকে সংগ্রহ করা হয়।",
      "Roshal Organic brings honey, ghee, jaggery, fruits, oils, and more natural foods to your home. Every product is sourced directly from farmers and natural producers.",
    ),
    ctaLabel: localizedValue("পণ্য দেখুন", "Browse products"),
    ctaHref: "/products",
    imageUrl: "/special-offer.jpg",
    items: [],
    styles: {
      highlight: "warm",
      density: "comfortable",
    },
  },
  {
    id: "section-home-promises",
    pageId: "page-home",
    sectionKey: "promises",
    type: "feature-grid",
    sortOrder: 1,
    layout: "grid",
    variant: "muted",
    isEnabled: true,
    eyebrow: localizedValue("আমাদের প্রতিশ্রুতি", "Our promises"),
    title: localizedValue(
      "বিশ্বাসে অটুট, স্বাদে আসল",
      "Reliable in trust, genuine in taste",
    ),
    body: localizedValue(
      "Roshal Organic যে কারণে আলাদা:",
      "Why Roshal Organic stands apart:",
    ),
    ctaLabel: localizedValue("আমাদের গল্প", "Read our story"),
    ctaHref: "/about",
    imageUrl: "",
    items: [
      {
        title: localizedValue("১০০% খাঁটি", "100% pure"),
        body: localizedValue(
          "ভেজালহীন ও যত্নে বাছাই করা পণ্য।",
          "Carefully sourced products with no adulteration.",
        ),
      },
      {
        title: localizedValue("কোনো কেমিক্যাল নেই", "No chemicals"),
        body: localizedValue(
          "কোনো প্রিজারভেটিভ বা ক্ষতিকর সংযোজন নেই।",
          "No preservatives or harmful additives.",
        ),
      },
      {
        title: localizedValue("সরাসরি উৎস থেকে", "Direct from source"),
        body: localizedValue(
          "দেশি কৃষক ও প্রাকৃতিক উৎপাদকদের সঙ্গে কাজ করি।",
          "We work directly with local farmers and natural producers.",
        ),
      },
      {
        title: localizedValue("পরিবারের জন্য নিরাপদ", "Safe for families"),
        body: localizedValue(
          "দৈনন্দিন সুস্থতার জন্য পুষ্টিকর খাবার।",
          "Nutritious foods for everyday wellbeing.",
        ),
      },
    ],
    styles: {
      columns: "4",
    },
  },
  {
    id: "section-home-featured",
    pageId: "page-home",
    sectionKey: "featured-products",
    type: "featured-products",
    sortOrder: 2,
    layout: "carousel",
    variant: "default",
    isEnabled: true,
    eyebrow: localizedValue("জনপ্রিয় পণ্য", "Popular products"),
    title: localizedValue("আজকের সেরা পছন্দ", "Today’s best picks"),
    body: localizedValue(
      "মধু, ঘি, গুড়, আম এবং রান্নাঘরের প্রয়োজনীয় খাঁটি পণ্য।",
      "Pure honey, ghee, jaggery, mangoes, and kitchen essentials.",
    ),
    ctaLabel: localizedValue("সব পণ্য", "All products"),
    ctaHref: "/products",
    imageUrl: "",
    items: [],
    styles: {
      productCount: "4",
    },
  },
  {
    id: "section-home-story",
    pageId: "page-home",
    sectionKey: "brand-story",
    type: "story",
    sortOrder: 3,
    layout: "split",
    variant: "muted",
    isEnabled: true,
    eyebrow: localizedValue("আমাদের গল্প", "Our story"),
    title: localizedValue(
      "প্রকৃতির কাছ থেকে পাওয়া খাবারই সবচেয়ে নিরাপদ",
      "Food from nature is the safest choice",
    ),
    body: localizedValue(
      "Roshal Organic একটি প্রাকৃতিক ও স্বাস্থ্যসম্মত খাদ্য ব্র্যান্ড, যেখানে আমাদের লক্ষ্য হলো রাসায়নিকমুক্ত, ভেজালহীন এবং স্বাস্থ্যকর খাবার সরবরাহ করা।",
      "Roshal Organic is a natural and healthy food brand built around delivering chemical-free, unadulterated, wholesome foods.",
    ),
    ctaLabel: localizedValue("আরও জানুন", "Learn more"),
    ctaHref: "/about",
    imageUrl: "/brand-story.jpg",
    items: [],
    styles: {
      emphasis: "editorial",
    },
  },
  {
    id: "section-home-categories",
    pageId: "page-home",
    sectionKey: "landing-categories",
    type: "feature-grid",
    sortOrder: 10,
    layout: "grid",
    variant: "default",
    isEnabled: true,
    eyebrow: localizedValue("", ""),
    title: localizedValue("বিশেষ ক্যাটাগরি", "Featured Categories"),
    body: localizedValue("", ""),
    ctaLabel: localizedValue("", ""),
    ctaHref: "",
    imageUrl: "",
    items: [
      {
        title: localizedValue("তেল ও ঘি", "Oil & Ghee"),
        imageUrl: "/oil-2.jpg",
        href: "/products?category=ghee",
      },
      {
        title: localizedValue("অর্গানিক", "Organic"),
        imageUrl: "/organic-vegetables.jpg",
        href: "/products",
      },
      {
        title: localizedValue("মধু", "Honey"),
        imageUrl: "/deal-3.jpg",
        href: "/products?category=honey",
      },
      {
        title: localizedValue("খেজুর", "Dates"),
        imageUrl: "/fruits.jpg",
        href: "/products?category=gur",
      },
      {
        title: localizedValue("মশলা", "Spices"),
        imageUrl: "/spices.jpg",
        href: "/products",
      },
      {
        title: localizedValue("বাদাম ও বীজ", "Nuts & Seeds"),
        imageUrl: "/dates-2.jpg",
        href: "/products",
      },
      {
        title: localizedValue("পানীয়", "Beverage"),
        imageUrl: "/tea.jpg",
        href: "/products",
      },
      {
        title: localizedValue("চাল", "Rice"),
        imageUrl: "/rice-bowl.jpg",
        href: "/products",
      },
    ],
    styles: {},
  },
  {
    id: "section-home-top-sellers",
    pageId: "page-home",
    sectionKey: "landing-top-sellers",
    type: "featured-products",
    sortOrder: 11,
    layout: "grid",
    variant: "muted",
    isEnabled: true,
    eyebrow: localizedValue("", ""),
    title: localizedValue("সেরা বিক্রেতা", "Top Sellers"),
    body: localizedValue(
      "ড্যাশবোর্ডে ফিচার্ড বা অগ্রাধিকারপ্রাপ্ত পণ্যগুলো এই ব্লকে দেখাতে পারবেন।",
      "Use this block for featured or priority products managed from the dashboard.",
    ),
    ctaLabel: localizedValue("আরও দেখুন", "View More"),
    ctaHref: "/products",
    imageUrl: "",
    items: [],
    styles: {
      source: "featured",
      limit: "8",
      offset: "0",
    },
  },
  {
    id: "section-home-new-arrivals",
    pageId: "page-home",
    sectionKey: "landing-new-arrivals",
    type: "featured-products",
    sortOrder: 12,
    layout: "grid",
    variant: "default",
    isEnabled: true,
    eyebrow: localizedValue("", ""),
    title: localizedValue("নতুন আগমন", "New Arrivals"),
    body: localizedValue(
      "নতুন বা নিচের অর্ডারের পণ্যগুলো এখানে দেখান।",
      "Show the newest or reverse-sorted products in this block.",
    ),
    ctaLabel: localizedValue("সব নতুন পণ্য দেখুন", "View All New Arrivals"),
    ctaHref: "/products",
    imageUrl: "",
    items: [],
    styles: {
      source: "reverse",
      limit: "8",
      offset: "0",
    },
  },
  {
    id: "section-home-special-offers",
    pageId: "page-home",
    sectionKey: "landing-special-offers",
    type: "feature-grid",
    sortOrder: 13,
    layout: "grid",
    variant: "muted",
    isEnabled: true,
    eyebrow: localizedValue("", ""),
    title: localizedValue("বিশেষ ডিল", "Special Deals"),
    body: localizedValue("", ""),
    ctaLabel: localizedValue("", ""),
    ctaHref: "",
    imageUrl: "",
    items: [
      {
        title: localizedValue("মধু বান্ডেল অফার", "Honey Bundle Offer"),
        body: localizedValue("৩টি মধু কিনে ১টি ফ্রি", "Buy 3 Get 1 Free"),
        imageUrl: "/deal-3.jpg",
        href: "/products/pure-honey",
        value: "25% OFF",
        label: localizedValue("অফারটি দেখুন", "View Offer"),
      },
      {
        title: localizedValue("ঘি বান্ডেল অফার", "Ghee Bundle Offer"),
        body: localizedValue("২টি ঘি কিনে ১০% ছাড়", "Buy 2 Get 10% Off"),
        imageUrl: "/oil-2.jpg",
        href: "/products/organic-ghee",
        value: "10% OFF",
        label: localizedValue("অফারটি দেখুন", "View Offer"),
      },
      {
        title: localizedValue("মশলা বান্ডেল অফার", "Spices Bundle Offer"),
        body: localizedValue("৫টি মশলা কিনে ১৫% ছাড়", "Buy 5 Get 15% Off"),
        imageUrl: "/spices.jpg",
        href: "/products",
        value: "15% OFF",
        label: localizedValue("অফারটি দেখুন", "View Offer"),
      },
    ],
    styles: {},
  },
  {
    id: "section-home-fresh-picks",
    pageId: "page-home",
    sectionKey: "landing-fresh-picks",
    type: "featured-products",
    sortOrder: 14,
    layout: "grid",
    variant: "default",
    isEnabled: true,
    eyebrow: localizedValue("", ""),
    title: localizedValue("তাজা পণ্য", "Fresh Picks"),
    body: localizedValue(
      "এই ব্লকে সাধারণ ক্যাটালগ থেকে প্রোডাক্ট দেখানো হয়।",
      "This block renders products from the main catalog.",
    ),
    ctaLabel: localizedValue("সব পণ্য দেখুন", "View All Products"),
    ctaHref: "/products",
    imageUrl: "",
    items: [],
    styles: {
      source: "all",
      limit: "10",
      offset: "0",
    },
  },
  {
    id: "section-home-organic-picks",
    pageId: "page-home",
    sectionKey: "landing-organic-picks",
    type: "featured-products",
    sortOrder: 15,
    layout: "grid",
    variant: "muted",
    isEnabled: true,
    eyebrow: localizedValue("", ""),
    title: localizedValue("অর্গানিক পণ্য", "Organic Products"),
    body: localizedValue(
      "ফিচার্ড পণ্য বা নির্বাচিত পণ্য এই ব্লকে দেখানোর জন্য `stylesJson` ব্যবহার করুন।",
      "Use `stylesJson` to show featured or hand-picked products in this block.",
    ),
    ctaLabel: localizedValue("সব অর্গানিক পণ্য দেখুন", "View All Organic Products"),
    ctaHref: "/products",
    imageUrl: "",
    items: [],
    styles: {
      source: "featured",
      limit: "10",
      offset: "0",
    },
  },
  {
    id: "section-home-seasonal-picks",
    pageId: "page-home",
    sectionKey: "landing-seasonal-picks",
    type: "featured-products",
    sortOrder: 16,
    layout: "grid",
    variant: "default",
    isEnabled: true,
    eyebrow: localizedValue("", ""),
    title: localizedValue("মৌসুমি পণ্য", "Seasonal Products"),
    body: localizedValue(
      "রিভার্স সোর্স বা অফসেট দিয়ে এই ব্লকের প্রোডাক্ট বদলান।",
      "Change the products in this block with reverse source or offset settings.",
    ),
    ctaLabel: localizedValue("সব মৌসুমি পণ্য দেখুন", "View All Seasonal Products"),
    ctaHref: "/products",
    imageUrl: "",
    items: [],
    styles: {
      source: "reverse",
      limit: "10",
      offset: "0",
    },
  },
  {
    id: "section-home-stats",
    pageId: "page-home",
    sectionKey: "landing-stats",
    type: "feature-grid",
    sortOrder: 17,
    layout: "grid",
    variant: "muted",
    isEnabled: true,
    eyebrow: localizedValue("", ""),
    title: localizedValue("আমাদের পরিসংখ্যান", "Our Numbers"),
    body: localizedValue("", ""),
    ctaLabel: localizedValue("", ""),
    ctaHref: "",
    imageUrl: "",
    items: [
      {
        label: localizedValue("সন্তুষ্ট গ্রাহক", "Happy Customers"),
        value: "10K+",
      },
      {
        label: localizedValue("পণ্য", "Products"),
        value: "500+",
      },
      {
        label: localizedValue("ক্যাটাগরি", "Categories"),
        value: "50+",
      },
      {
        label: localizedValue("মান নিশ্চিত", "Quality Assured"),
        value: "99%",
      },
    ],
    styles: {},
  },
  {
    id: "section-about-intro",
    pageId: "page-about",
    sectionKey: "intro",
    type: "story",
    sortOrder: 0,
    layout: "split",
    variant: "default",
    isEnabled: true,
    eyebrow: localizedValue("Roshal Organic", "Roshal Organic"),
    title: localizedValue(
      "প্রাকৃতিক ও স্বাস্থ্যসম্মত খাদ্যের ব্র্যান্ড",
      "A brand for natural and healthy food",
    ),
    body: localizedValue(
      "আমরা বিশ্বাস করি প্রকৃতির কাছ থেকে পাওয়া খাবারই সবচেয়ে নিরাপদ ও পুষ্টিকর। তাই আমরা দেশি কৃষক ও প্রাকৃতিক উৎস থেকে সংগ্রহ করা পণ্য নিয়ে কাজ করি।",
      "We believe food sourced from nature is the safest and most nourishing. That is why we work with local farmers and natural producers.",
    ),
    ctaLabel: localizedValue("যোগাযোগ করুন", "Talk to us"),
    ctaHref: "/contact",
    imageUrl: "/organic-benefits.jpg",
    items: [],
    styles: {
      emphasis: "balanced",
    },
  },
  {
    id: "section-about-commitments",
    pageId: "page-about",
    sectionKey: "commitments",
    type: "feature-grid",
    sortOrder: 1,
    layout: "grid",
    variant: "soft",
    isEnabled: true,
    eyebrow: localizedValue("আমাদের লক্ষ্য ও প্রতিশ্রুতি", "Mission and promises"),
    title: localizedValue(
      "স্বাস্থ্যকর জীবনযাপনে আস্থা গড়ে তোলা",
      "Build confidence in healthier living",
    ),
    body: localizedValue(
      "আমাদের কাজের মূল প্রতিশ্রুতিগুলো:",
      "The commitments at the center of our work:",
    ),
    ctaLabel: localizedValue("পণ্য দেখুন", "Shop products"),
    ctaHref: "/products",
    imageUrl: "",
    items: [
      {
        title: localizedValue("খাঁটি ও প্রাকৃতিক", "Pure and natural"),
        body: localizedValue(
          "প্রতিটি পণ্য আসল মান নিশ্চিত করে বাছাই করা হয়।",
          "Every product is selected with authenticity in mind.",
        ),
      },
      {
        title: localizedValue("কোনো প্রিজারভেটিভ নেই", "No preservatives"),
        body: localizedValue(
          "কৃত্রিম সংযোজন ছাড়া পরিচ্ছন্ন খাদ্য।",
          "Clean food without artificial additives.",
        ),
      },
      {
        title: localizedValue("সরাসরি সংগ্রহ", "Direct sourcing"),
        body: localizedValue(
          "কৃষক, মৌচাষি ও কারিগরদের কাছ থেকে সংগ্রহ।",
          "Directly sourced from farmers, beekeepers, and makers.",
        ),
      },
      {
        title: localizedValue("গ্রাহককেন্দ্রিক", "Customer focused"),
        body: localizedValue(
          "পরিবারের জন্য নিরাপদ ও বিশ্বস্ত খাবার।",
          "Safe, dependable foods for families.",
        ),
      },
    ],
    styles: {
      columns: "2",
    },
  },
  {
    id: "section-contact-details",
    pageId: "page-contact",
    sectionKey: "details",
    type: "contact-cards",
    sortOrder: 1,
    layout: "grid",
    variant: "default",
    isEnabled: true,
    eyebrow: localizedValue("যোগাযোগ", "Contact"),
    title: localizedValue(
      "অর্ডার, সহায়তা বা পাইকারি জিজ্ঞাসার জন্য",
      "For orders, support, or wholesale requests",
    ),
    body: localizedValue(
      "আমরা কল, ইমেইল এবং হোয়াটসঅ্যাপে দ্রুত সাড়া দিই।",
      "We respond quickly over calls, email, and WhatsApp.",
    ),
    ctaLabel: localizedValue("হোয়াটসঅ্যাপ করুন", "Message on WhatsApp"),
    ctaHref: "https://wa.me/8801805767300",
    imageUrl: "",
    items: [
      {
        label: localizedValue("ফোন", "Phone"),
        value: "+880 1719-403627",
      },
      {
        label: localizedValue("ইমেইল", "Email"),
        value: "info@roshalorganic.com",
      },
      {
        label: localizedValue("ঠিকানা", "Address"),
        value: "ঢাকা, বাংলাদেশ",
      },
      {
        label: localizedValue("সাপোর্ট সময়", "Support hours"),
        value: "9:00 AM - 8:00 PM",
      },
    ],
    styles: {
      columns: "2",
    },
  },
  ...defaultRoshalCorePageEnhancements,
  ...defaultRoshalExtendedSections,
];

export const defaultRoshalProducts: RoshalProduct[] = [
  {
    id: "product-honey",
    slug: "pure-honey",
    sku: "RO-HONEY-001",
    name: localizedValue("খাঁটি মধু", "Pure Honey"),
    summary: localizedValue(
      "গ্রামবাংলার খাঁটি ও প্রাকৃতিক মধু।",
      "Pure, natural honey sourced from rural Bangladesh.",
    ),
    description: localizedValue(
      "খাঁটি স্বাদের মধু যা কোনো প্রিজারভেটিভ বা ভেজাল ছাড়াই সংগ্রহ করা হয়। সকালের খাবার, চা, বা ঘরোয়া স্বাস্থ্যচর্চায় উপযোগী।",
      "Pure honey gathered without preservatives or adulteration. Ideal for breakfast, tea, or everyday wellness rituals.",
    ),
    categoryKey: "honey",
    categoryLabel: localizedValue("মধু", "Honey"),
    price: 450,
    compareAtPrice: 520,
    inventory: 18,
    badge: "bestseller",
    heroImage: "/deal-3.jpg",
    gallery: ["/deal-3.jpg", "/walnuts.jpg"],
    features: [
      localizedValue("১০০% খাঁটি", "100% pure"),
      localizedValue("কেমিক্যালমুক্ত", "Chemical-free"),
      localizedValue("সরাসরি মৌচাষি থেকে", "Direct from beekeepers"),
    ],
    isFeatured: true,
    isPublished: true,
    sortOrder: 0,
  },
  {
    id: "product-ghee",
    slug: "organic-ghee",
    sku: "RO-GHEE-001",
    name: localizedValue("অর্গানিক ঘি", "Organic Ghee"),
    summary: localizedValue(
      "খাঁটি দুধ থেকে তৈরি সুগন্ধি ঘি।",
      "Aromatic ghee made from pure milk.",
    ),
    description: localizedValue(
      "ঐতিহ্যবাহী পদ্ধতিতে প্রস্তুত করা ঘি যা রান্না, ভাত, খিচুড়ি ও নাস্তার সঙ্গে অসাধারণ মানিয়ে যায়।",
      "Crafted through a traditional process for rich cooking, rice, khichuri, and breakfast use.",
    ),
    categoryKey: "ghee",
    categoryLabel: localizedValue("ঘি", "Ghee"),
    price: 800,
    compareAtPrice: 880,
    inventory: 9,
    badge: "premium",
    heroImage: "/oil-2.jpg",
    gallery: ["/oil-2.jpg", "/olive-oil.jpg"],
    features: [
      localizedValue("ঐতিহ্যবাহী প্রস্তুতি", "Traditional preparation"),
      localizedValue("গভীর স্বাদ", "Rich flavor"),
      localizedValue("পরিবারের জন্য নিরাপদ", "Safe for families"),
    ],
    isFeatured: true,
    isPublished: true,
    sortOrder: 1,
  },
  {
    id: "product-jaggery",
    slug: "deshi-gur",
    sku: "RO-GUR-001",
    name: localizedValue("দেশি গুড়", "Traditional Jaggery"),
    summary: localizedValue(
      "খেজুর ও তাল থেকে তৈরি দেশি গুড়।",
      "Traditional jaggery made from date and palm sap.",
    ),
    description: localizedValue(
      "শীতের নাস্তা, পিঠা, চা এবং ঘরোয়া রান্নায় খাঁটি মিষ্টতার জন্য আদর্শ।",
      "Perfect for winter breakfasts, pitha, tea, and home cooking with a genuine sweetness.",
    ),
    categoryKey: "gur",
    categoryLabel: localizedValue("গুড়", "Jaggery"),
    price: 280,
    compareAtPrice: 330,
    inventory: 24,
    badge: "seasonal",
    heroImage: "/fruits.jpg",
    gallery: ["/fruits.jpg", "/mango-2.jpg"],
    features: [
      localizedValue("ঋতুভিত্তিক সংগ্রহ", "Seasonally sourced"),
      localizedValue("খাঁটি স্বাদ", "Authentic taste"),
      localizedValue("ঘরোয়া রান্নার সেরা সঙ্গী", "Perfect for home recipes"),
    ],
    isFeatured: true,
    isPublished: true,
    sortOrder: 2,
  },
  {
    id: "product-mango",
    slug: "seasonal-mango",
    sku: "RO-MANGO-001",
    name: localizedValue("মৌসুমি আম", "Seasonal Mango"),
    summary: localizedValue(
      "বাগান থেকে সংগ্রহ করা নির্বাচিত আম।",
      "Selected mangoes sourced directly from orchards.",
    ),
    description: localizedValue(
      "মৌসুমের সেরা আম, যা প্রাকৃতিকভাবে পাকানো এবং পরিবারে ভাগ করে খাওয়ার জন্য আদর্শ।",
      "The season’s best mangoes, naturally ripened and ideal for sharing at home.",
    ),
    categoryKey: "fruit",
    categoryLabel: localizedValue("ফল", "Fruit"),
    price: 360,
    compareAtPrice: 420,
    inventory: 30,
    badge: "fresh",
    heroImage: "/mango-2.jpg",
    gallery: ["/mango-2.jpg", "/mango.jpg"],
    features: [
      localizedValue("মৌসুমভিত্তিক", "Seasonal"),
      localizedValue("রাসায়নিকমুক্ত", "Chemical-free"),
      localizedValue("সরাসরি বাগান থেকে", "Direct from orchards"),
    ],
    isFeatured: true,
    isPublished: true,
    sortOrder: 3,
  },
  {
    id: "product-oil",
    slug: "natural-mustard-oil",
    sku: "RO-OIL-001",
    name: localizedValue("প্রাকৃতিক সরিষার তেল", "Natural Mustard Oil"),
    summary: localizedValue(
      "রান্নাঘরের জন্য কোল্ড-প্রেসড তেল।",
      "Cold-pressed mustard oil for everyday cooking.",
    ),
    description: localizedValue(
      "খাঁটি সরিষার তেল যা ঘরোয়া রান্নায় সুগন্ধ, রঙ এবং স্বাদ বাড়ায়।",
      "Pure mustard oil that lifts aroma, color, and taste in home cooking.",
    ),
    categoryKey: "oil",
    categoryLabel: localizedValue("তেল", "Oil"),
    price: 320,
    compareAtPrice: 370,
    inventory: 15,
    badge: "kitchen-staple",
    heroImage: "/oil-2.jpg",
    gallery: ["/oil-2.jpg", "/olive-oil.jpg"],
    features: [
      localizedValue("কোল্ড-প্রেসড", "Cold-pressed"),
      localizedValue("তীব্র সুগন্ধ", "Bold aroma"),
      localizedValue("দৈনন্দিন রান্নায় উপযোগী", "Great for daily cooking"),
    ],
    isFeatured: false,
    isPublished: true,
    sortOrder: 4,
  },
  {
    id: "product-yogurt",
    slug: "fresh-yogurt",
    sku: "RO-YOGURT-001",
    name: localizedValue("ফ্রেশ দই", "Fresh Yogurt"),
    summary: localizedValue(
      "দুধের স্বাদ ধরে রাখা টাটকা দই।",
      "Fresh yogurt that keeps the taste of real milk.",
    ),
    description: localizedValue(
      "ঘন, মসৃণ এবং টাটকা দই যা সকালের নাস্তা কিংবা ভাতের সঙ্গে দারুণ লাগে।",
      "Thick, smooth yogurt that works well for breakfast or alongside meals.",
    ),
    categoryKey: "dairy",
    categoryLabel: localizedValue("দুগ্ধজাত", "Dairy"),
    price: 160,
    compareAtPrice: null,
    inventory: 12,
    badge: "fresh",
    heroImage: "/yogurt-2.jpg",
    gallery: ["/yogurt-2.jpg", "/yogurt.jpg"],
    features: [
      localizedValue("টাটকা", "Fresh"),
      localizedValue("খাঁটি দুধ থেকে", "Made from pure milk"),
      localizedValue("প্রতিদিনের জন্য", "Great for daily use"),
    ],
    isFeatured: false,
    isPublished: true,
    sortOrder: 5,
  },
  ...vegetableProducts,
];

export const defaultRoshalPaymentSettings: RoshalPaymentSettings = {
  id: "payment-settings",
  manualReviewNotice: localizedValue(
    "পেমেন্ট করার পর ট্রানজ্যাকশন আইডি এবং স্ক্রিনশট দিন। অ্যাডমিন যাচাই করে অর্ডার কনফার্ম করবে।",
    "Submit your transaction ID and payment proof after payment. An admin will verify it before the order is confirmed.",
  ),
  supportMessage: localizedValue(
    "কোনো সমস্যা হলে Roshal Organic সাপোর্ট টিমের সাথে যোগাযোগ করুন।",
    "Contact the Roshal Organic support team if you need help with payment.",
  ),
  options: [
    {
      key: "cash_on_delivery",
      enabled: true,
      mode: "manual",
      label: localizedValue("ক্যাশ অন ডেলিভারি", "Cash on delivery"),
      merchantLabel: localizedValue("ডেলিভারির সময় পেমেন্ট", "Pay on delivery"),
      accountType: "cash-on-delivery",
      accountNumber: "",
      instructions: localizedValue(
        "অর্ডার রিসিভ করার সময় ডেলিভারি ম্যানকে ক্যাশে পেমেন্ট করুন।",
        "Pay the delivery agent in cash when the order arrives.",
      ),
      guideImageUrl: "",
      requiresProof: false,
      sortOrder: 0,
    },
    {
      key: "card",
      enabled: true,
      mode: "gateway",
      label: localizedValue("কার্ড", "Card"),
      merchantLabel: localizedValue("সিকিউর কার্ড পেমেন্ট", "Secure card payment"),
      accountType: "card-gateway",
      accountNumber: "",
      instructions: localizedValue(
        "কার্ড গেটওয়ে কনফিগার হলে এখানে সরাসরি পেমেন্ট চালু হবে। এর মধ্যে অর্ডার সাবমিট করে সাপোর্ট টিমের নির্দেশনা অনুসরণ করুন।",
        "Once a card gateway is configured, direct card payment will appear here. Until then, submit the order and follow the support instructions.",
      ),
      guideImageUrl: "",
      requiresProof: false,
      sortOrder: 1,
    },
    {
      key: "bkash",
      enabled: true,
      mode: "manual",
      label: localizedValue("বিকাশ", "bKash"),
      merchantLabel: localizedValue(
        "বিকাশ মার্চেন্ট/পার্সোনাল",
        "bKash merchant/personal",
      ),
      accountType: "mobile-wallet",
      accountNumber: "",
      instructions: localizedValue(
        "ড্যাশবোর্ড থেকে বিকাশ নাম্বার, রেফারেন্স এবং গাইড ইমেজ আপডেট করুন। গ্রাহককে ট্রানজ্যাকশন আইডি ও স্ক্রিনশট দিতে বলুন।",
        "Update the bKash number, reference instructions, and guide image from the dashboard. Ask customers to submit their transaction ID and payment screenshot.",
      ),
      guideImageUrl: "",
      requiresProof: true,
      sortOrder: 2,
    },
    {
      key: "nagad",
      enabled: true,
      mode: "manual",
      label: localizedValue("নগদ", "Nagad"),
      merchantLabel: localizedValue(
        "নগদ মার্চেন্ট/পার্সোনাল",
        "Nagad merchant/personal",
      ),
      accountType: "mobile-wallet",
      accountNumber: "",
      instructions: localizedValue(
        "ড্যাশবোর্ড থেকে নগদ নাম্বার ও গাইড আপডেট করুন। গ্রাহক ট্রানজ্যাকশন আইডি এবং পেমেন্ট প্রুফ জমা দেবে।",
        "Update the Nagad number and guide from the dashboard. Customers will submit their transaction ID and payment proof.",
      ),
      guideImageUrl: "",
      requiresProof: true,
      sortOrder: 3,
    },
    {
      key: "rocket",
      enabled: true,
      mode: "manual",
      label: localizedValue("রকেট", "Rocket"),
      merchantLabel: localizedValue(
        "রকেট মার্চেন্ট/পার্সোনাল",
        "Rocket merchant/personal",
      ),
      accountType: "mobile-wallet",
      accountNumber: "",
      instructions: localizedValue(
        "ড্যাশবোর্ড থেকে রকেট নাম্বার ও গাইড আপডেট করুন। গ্রাহক ট্রানজ্যাকশন আইডি এবং স্ক্রিনশট আপলোড করবে।",
        "Update the Rocket number and guide from the dashboard. Customers will upload their transaction ID and screenshot.",
      ),
      guideImageUrl: "",
      requiresProof: true,
      sortOrder: 4,
    },
    {
      key: "upay",
      enabled: true,
      mode: "gateway",
      label: localizedValue("উপায়", "Upay"),
      merchantLabel: localizedValue("উপায় গেটওয়ে", "Upay gateway"),
      accountType: "mobile-wallet",
      accountNumber: "",
      instructions: localizedValue(
        "উপায় গেটওয়ে চালু থাকলে চেকআউটে aamarPay রিডাইরেক্ট হবে। প্রয়োজন হলে অ্যাডমিন ড্যাশবোর্ড থেকে এটিকে ম্যানুয়াল মোডে পরিবর্তন করতে পারবেন।",
        "When Upay gateway checkout is enabled, customers will be redirected through aamarPay. Admins can switch this option to manual mode from the dashboard if needed.",
      ),
      guideImageUrl: "",
      requiresProof: false,
      sortOrder: 4,
    },
  ],
};
