import { localizedValue } from "@/lib/store-locale";
import type {
  RoshalStoreCategory,
  RoshalStoreSubcategory,
} from "@/lib/store-types";

function createCategory({
  id,
  key,
  labelBn,
  labelEn,
  descriptionBn,
  descriptionEn,
  imageUrl,
  sourceKeys,
  sortOrder,
  showOnHomepage = true,
}: {
  id: string;
  key: string;
  labelBn: string;
  labelEn: string;
  descriptionBn: string;
  descriptionEn: string;
  imageUrl: string;
  sourceKeys: string[];
  sortOrder: number;
  showOnHomepage?: boolean;
}): RoshalStoreCategory {
  return {
    id,
    key,
    label: localizedValue(labelBn, labelEn),
    description: localizedValue(descriptionBn, descriptionEn),
    imageUrl,
    sourceKeys,
    isEnabled: true,
    showInNavigation: true,
    showOnHomepage,
    sortOrder,
  };
}

function createSubcategory({
  id,
  categoryId,
  categoryKey,
  key,
  labelBn,
  labelEn,
  descriptionBn,
  descriptionEn,
  imageUrl,
  sourceKeys,
  sortOrder,
}: {
  id: string;
  categoryId: string;
  categoryKey: string;
  key: string;
  labelBn: string;
  labelEn: string;
  descriptionBn: string;
  descriptionEn: string;
  imageUrl: string;
  sourceKeys: string[];
  sortOrder: number;
}): RoshalStoreSubcategory {
  return {
    id,
    categoryId,
    categoryKey,
    key,
    label: localizedValue(labelBn, labelEn),
    description: localizedValue(descriptionBn, descriptionEn),
    imageUrl,
    sourceKeys,
    isEnabled: true,
    showInNavigation: true,
    sortOrder,
  };
}

export const defaultRoshalCategories: RoshalStoreCategory[] = [
  createCategory({
    id: "category-oil-ghee",
    key: "oil-ghee",
    labelBn: "তেল ও ঘি",
    labelEn: "Oil & Ghee",
    descriptionBn: "সরিষার তেল, ঘি এবং রান্নাঘরের প্রিমিয়াম প্রয়োজনীয় পণ্য।",
    descriptionEn: "Mustard oil, ghee, and premium cooking essentials.",
    imageUrl: "/oil-2.jpg",
    sourceKeys: ["oil", "ghee"],
    sortOrder: 0,
  }),
  createCategory({
    id: "category-honey",
    key: "honey",
    labelBn: "মধু",
    labelEn: "Honey",
    descriptionBn: "খাঁটি, কেমিক্যালমুক্ত এবং ওয়েলনেস-কেন্দ্রিক মধুর সংগ্রহ।",
    descriptionEn: "Pure, chemical-free honey for everyday wellness.",
    imageUrl: "/deal-3.jpg",
    sourceKeys: ["honey"],
    sortOrder: 1,
  }),
  createCategory({
    id: "category-fruits-dates",
    key: "fruits-dates",
    labelBn: "ফল ও খেজুর",
    labelEn: "Fruits & Dates",
    descriptionBn: "মৌসুমী ফল, খেজুর এবং প্রাকৃতিক মিষ্টি স্ন্যাকস।",
    descriptionEn: "Seasonal fruit, dates, and naturally sweet snack picks.",
    imageUrl: "/mango-2.jpg",
    sourceKeys: ["fruit"],
    sortOrder: 2,
  }),
  createCategory({
    id: "category-jaggery-sweeteners",
    key: "jaggery-sweeteners",
    labelBn: "গুড় ও সুইটেনার",
    labelEn: "Jaggery & Sweeteners",
    descriptionBn: "দেশি গুড়, প্রাকৃতিক মিষ্টি এবং শীতের রান্নার পছন্দ।",
    descriptionEn: "Traditional jaggery and natural sweeteners for the pantry.",
    imageUrl: "/fruits.jpg",
    sourceKeys: ["gur"],
    sortOrder: 3,
  }),
  createCategory({
    id: "category-dairy-breakfast",
    key: "dairy-breakfast",
    labelBn: "দুগ্ধ ও ব্রেকফাস্ট",
    labelEn: "Dairy & Breakfast",
    descriptionBn: "দই এবং সকালের টেবিলের নির্ভরযোগ্য দুগ্ধজাত পণ্য।",
    descriptionEn: "Fresh yogurt and breakfast-friendly dairy staples.",
    imageUrl: "/yogurt-2.jpg",
    sourceKeys: ["dairy"],
    sortOrder: 4,
  }),
  createCategory({
    id: "category-fresh-vegetables",
    key: "fresh-vegetables",
    labelBn: "তাজা সবজি",
    labelEn: "Fresh Vegetables",
    descriptionBn: "প্রতিদিনের বাজারের জন্য তাজা সবজির লাইভ সংগ্রহ।",
    descriptionEn:
      "A live vegetables collection for the everyday market basket.",
    imageUrl: "/organic-vegetables.jpg",
    sourceKeys: ["vegetables"],
    sortOrder: 5,
  }),
  createCategory({
    id: "category-organic-certified",
    key: "organic-certified",
    labelBn: "অর্গানিক ও সার্টিফায়েড",
    labelEn: "Organic & Certified",
    descriptionBn: "অর্গানিক, সার্টিফায়েড এবং ওয়েলনেস-কেন্দ্রিক পণ্য।",
    descriptionEn: "Organic, certified, and wellness-focused products.",
    imageUrl: "/special-offer.jpg",
    sourceKeys: ["vegetables", "honey", "fruit", "dairy"],
    sortOrder: 6,
  }),
  createCategory({
    id: "category-kitchen-essentials",
    key: "kitchen-essentials",
    labelBn: "কিচেন এসেনশিয়াল",
    labelEn: "Kitchen Essentials",
    descriptionBn: "রান্নাঘরের নিয়মিত প্রয়োজনীয় খাঁটি পছন্দ।",
    descriptionEn: "Daily cooking staples and reliable kitchen basics.",
    imageUrl: "/spices.jpg",
    sourceKeys: ["oil", "ghee", "gur", "dairy"],
    sortOrder: 7,
  }),
  createCategory({
    id: "category-wellness-picks",
    key: "wellness-picks",
    labelBn: "ওয়েলনেস পিকস",
    labelEn: "Wellness Picks",
    descriptionBn: "ইমিউনিটি, এনার্জি এবং প্রাকৃতিক পুষ্টির নির্বাচিত পণ্য।",
    descriptionEn: "Curated picks for immunity, energy, and natural nutrition.",
    imageUrl: "/tea.jpg",
    sourceKeys: ["honey", "fruit", "vegetables"],
    sortOrder: 8,
    showOnHomepage: false,
  }),
];

export const defaultRoshalSubcategories: RoshalStoreSubcategory[] = [
  createSubcategory({
    id: "subcategory-mustard-oil",
    categoryId: "category-oil-ghee",
    categoryKey: "oil-ghee",
    key: "mustard-oil",
    labelBn: "সরিষার তেল",
    labelEn: "Mustard Oil",
    descriptionBn: "রান্নার জন্য দেশি সরিষার তেল।",
    descriptionEn: "Traditional mustard oil for everyday cooking.",
    imageUrl: "/oil-2.jpg",
    sourceKeys: ["oil"],
    sortOrder: 0,
  }),
  createSubcategory({
    id: "subcategory-cold-pressed-oil",
    categoryId: "category-oil-ghee",
    categoryKey: "oil-ghee",
    key: "cold-pressed-oil",
    labelBn: "কোল্ড-প্রেসড তেল",
    labelEn: "Cold-Pressed Oil",
    descriptionBn: "স্বাদ ও গন্ধ বজায় রাখা তেলের সংগ্রহ।",
    descriptionEn: "Oils that keep their natural flavor and aroma.",
    imageUrl: "/olive-oil.jpg",
    sourceKeys: ["oil"],
    sortOrder: 1,
  }),
  createSubcategory({
    id: "subcategory-olive-oil-blends",
    categoryId: "category-oil-ghee",
    categoryKey: "oil-ghee",
    key: "olive-oil-blends",
    labelBn: "অলিভ অয়েল ব্লেন্ড",
    labelEn: "Olive Oil Blends",
    descriptionBn: "রোস্ট, সালাদ এবং প্রিমিয়াম রান্নার জন্য।",
    descriptionEn: "For roasts, salads, and premium kitchen use.",
    imageUrl: "/olive-oil.jpg",
    sourceKeys: ["oil"],
    sortOrder: 2,
  }),
  createSubcategory({
    id: "subcategory-pure-ghee",
    categoryId: "category-oil-ghee",
    categoryKey: "oil-ghee",
    key: "pure-ghee",
    labelBn: "খাঁটি ঘি",
    labelEn: "Pure Ghee",
    descriptionBn: "খাঁটি দুধের ঘন ঘি।",
    descriptionEn: "Rich ghee made from pure milk.",
    imageUrl: "/oil-2.jpg",
    sourceKeys: ["ghee"],
    sortOrder: 3,
  }),
  createSubcategory({
    id: "subcategory-cooking-essentials",
    categoryId: "category-oil-ghee",
    categoryKey: "oil-ghee",
    key: "cooking-essentials",
    labelBn: "কুকিং এসেনশিয়াল",
    labelEn: "Cooking Essentials",
    descriptionBn: "ঘি ও তেলের মিশ্র কিচেন কালেকশন।",
    descriptionEn: "A combined kitchen collection of oils and ghee.",
    imageUrl: "/spices.jpg",
    sourceKeys: ["oil", "ghee"],
    sortOrder: 4,
  }),

  createSubcategory({
    id: "subcategory-raw-honey",
    categoryId: "category-honey",
    categoryKey: "honey",
    key: "raw-honey",
    labelBn: "র' মধু",
    labelEn: "Raw Honey",
    descriptionBn: "দৈনন্দিন ব্যবহারের খাঁটি মধু।",
    descriptionEn: "Pure honey for daily use.",
    imageUrl: "/deal-3.jpg",
    sourceKeys: ["honey"],
    sortOrder: 0,
  }),
  createSubcategory({
    id: "subcategory-black-seed-honey",
    categoryId: "category-honey",
    categoryKey: "honey",
    key: "black-seed-honey",
    labelBn: "কালোজিরা মধু",
    labelEn: "Black Seed Honey",
    descriptionBn: "ওয়েলনেস-কেন্দ্রিক মধুর পছন্দ।",
    descriptionEn: "A wellness-focused honey selection.",
    imageUrl: "/deal-3.jpg",
    sourceKeys: ["honey"],
    sortOrder: 1,
  }),
  createSubcategory({
    id: "subcategory-floral-honey",
    categoryId: "category-honey",
    categoryKey: "honey",
    key: "floral-honey",
    labelBn: "ফ্লোরাল হানি",
    labelEn: "Floral Honey",
    descriptionBn: "হালকা সুগন্ধি ফুলের স্বাদের মধু।",
    descriptionEn: "Light floral honey with a fragrant finish.",
    imageUrl: "/deal-3.jpg",
    sourceKeys: ["honey"],
    sortOrder: 2,
  }),
  createSubcategory({
    id: "subcategory-wellness-honey",
    categoryId: "category-honey",
    categoryKey: "honey",
    key: "wellness-honey",
    labelBn: "ওয়েলনেস হানি",
    labelEn: "Wellness Honey",
    descriptionBn: "সকালের রুটিন ও স্বাস্থ্যচর্চার জন্য।",
    descriptionEn: "For morning rituals and wellness routines.",
    imageUrl: "/deal-3.jpg",
    sourceKeys: ["honey"],
    sortOrder: 3,
  }),
  createSubcategory({
    id: "subcategory-honey-combos",
    categoryId: "category-honey",
    categoryKey: "honey",
    key: "honey-combos",
    labelBn: "হানি কম্বো",
    labelEn: "Honey Combos",
    descriptionBn: "উপহার ও পরিবারিক প্যাক।",
    descriptionEn: "Giftable and family-friendly honey packs.",
    imageUrl: "/deal-3.jpg",
    sourceKeys: ["honey"],
    sortOrder: 4,
  }),

  createSubcategory({
    id: "subcategory-seasonal-fruit",
    categoryId: "category-fruits-dates",
    categoryKey: "fruits-dates",
    key: "seasonal-fruit",
    labelBn: "মৌসুমি ফল",
    labelEn: "Seasonal Fruit",
    descriptionBn: "তাজা বাগানের ফল।",
    descriptionEn: "Fresh seasonal orchard picks.",
    imageUrl: "/mango-2.jpg",
    sourceKeys: ["fruit"],
    sortOrder: 0,
  }),
  createSubcategory({
    id: "subcategory-premium-mango",
    categoryId: "category-fruits-dates",
    categoryKey: "fruits-dates",
    key: "premium-mango",
    labelBn: "প্রিমিয়াম আম",
    labelEn: "Premium Mango",
    descriptionBn: "নির্বাচিত মানের আম।",
    descriptionEn: "Selected mangoes with premium ripeness.",
    imageUrl: "/mango.jpg",
    sourceKeys: ["fruit"],
    sortOrder: 1,
  }),
  createSubcategory({
    id: "subcategory-premium-dates",
    categoryId: "category-fruits-dates",
    categoryKey: "fruits-dates",
    key: "premium-dates",
    labelBn: "প্রিমিয়াম খেজুর",
    labelEn: "Premium Dates",
    descriptionBn: "উপহার ও রমজানের পছন্দ।",
    descriptionEn: "A classic choice for gifting and Ramadan tables.",
    imageUrl: "/dates-2.jpg",
    sourceKeys: ["fruit"],
    sortOrder: 2,
  }),
  createSubcategory({
    id: "subcategory-fruit-boxes",
    categoryId: "category-fruits-dates",
    categoryKey: "fruits-dates",
    key: "fruit-boxes",
    labelBn: "ফ্রুট বক্স",
    labelEn: "Fruit Boxes",
    descriptionBn: "পরিবারের জন্য মিক্সড ফ্রুট নির্বাচন।",
    descriptionEn: "Mixed fruit selections for the whole family.",
    imageUrl: "/fruits.jpg",
    sourceKeys: ["fruit"],
    sortOrder: 3,
  }),
  createSubcategory({
    id: "subcategory-juice-fruits",
    categoryId: "category-fruits-dates",
    categoryKey: "fruits-dates",
    key: "juice-fruits",
    labelBn: "জুস ফল",
    labelEn: "Juice Fruits",
    descriptionBn: "জুস ও ব্লেন্ডের জন্য উপযোগী ফল।",
    descriptionEn: "Fruit picks suitable for juice and smoothie blends.",
    imageUrl: "/fruits.jpg",
    sourceKeys: ["fruit"],
    sortOrder: 4,
  }),

  createSubcategory({
    id: "subcategory-date-jaggery",
    categoryId: "category-jaggery-sweeteners",
    categoryKey: "jaggery-sweeteners",
    key: "date-jaggery",
    labelBn: "খেজুরের গুড়",
    labelEn: "Date Jaggery",
    descriptionBn: "শীতকালীন নাশতার পছন্দ।",
    descriptionEn: "A winter staple for breakfast and desserts.",
    imageUrl: "/fruits.jpg",
    sourceKeys: ["gur"],
    sortOrder: 0,
  }),
  createSubcategory({
    id: "subcategory-palm-jaggery",
    categoryId: "category-jaggery-sweeteners",
    categoryKey: "jaggery-sweeteners",
    key: "palm-jaggery",
    labelBn: "তালের গুড়",
    labelEn: "Palm Jaggery",
    descriptionBn: "দেশি মিষ্টির ঐতিহ্যবাহী স্বাদ।",
    descriptionEn: "Traditional palm jaggery for classic sweets.",
    imageUrl: "/fruits.jpg",
    sourceKeys: ["gur"],
    sortOrder: 1,
  }),
  createSubcategory({
    id: "subcategory-liquid-jaggery",
    categoryId: "category-jaggery-sweeteners",
    categoryKey: "jaggery-sweeteners",
    key: "liquid-jaggery",
    labelBn: "লিকুইড গুড়",
    labelEn: "Liquid Jaggery",
    descriptionBn: "ডেজার্ট ও হট ড্রিঙ্কে মিশিয়ে খাওয়ার জন্য।",
    descriptionEn: "A liquid sweetener for desserts and hot drinks.",
    imageUrl: "/fruits.jpg",
    sourceKeys: ["gur"],
    sortOrder: 2,
  }),
  createSubcategory({
    id: "subcategory-breakfast-sweeteners",
    categoryId: "category-jaggery-sweeteners",
    categoryKey: "jaggery-sweeteners",
    key: "breakfast-sweeteners",
    labelBn: "ব্রেকফাস্ট সুইটেনার",
    labelEn: "Breakfast Sweeteners",
    descriptionBn: "চা, পিঠা ও সকালের নাশতার জন্য।",
    descriptionEn: "Perfect for tea, pitha, and breakfast dishes.",
    imageUrl: "/tea.jpg",
    sourceKeys: ["gur"],
    sortOrder: 3,
  }),
  createSubcategory({
    id: "subcategory-winter-pitha",
    categoryId: "category-jaggery-sweeteners",
    categoryKey: "jaggery-sweeteners",
    key: "winter-pitha",
    labelBn: "শীতের পিঠা",
    labelEn: "Winter Pitha Picks",
    descriptionBn: "পিঠাপুলির রান্নার উপযোগী নির্বাচন।",
    descriptionEn: "Curated jaggery picks for winter pitha recipes.",
    imageUrl: "/fruits.jpg",
    sourceKeys: ["gur"],
    sortOrder: 4,
  }),

  createSubcategory({
    id: "subcategory-fresh-yogurt",
    categoryId: "category-dairy-breakfast",
    categoryKey: "dairy-breakfast",
    key: "fresh-yogurt",
    labelBn: "ফ্রেশ দই",
    labelEn: "Fresh Yogurt",
    descriptionBn: "প্রতিদিনের জন্য টাটকা দই।",
    descriptionEn: "Fresh yogurt for everyday meals.",
    imageUrl: "/yogurt-2.jpg",
    sourceKeys: ["dairy"],
    sortOrder: 0,
  }),
  createSubcategory({
    id: "subcategory-mishti-doi",
    categoryId: "category-dairy-breakfast",
    categoryKey: "dairy-breakfast",
    key: "mishti-doi",
    labelBn: "মিষ্টি দই",
    labelEn: "Sweet Yogurt",
    descriptionBn: "ডেজার্ট-স্টাইল মিষ্টি দই।",
    descriptionEn: "Dessert-style sweet yogurt.",
    imageUrl: "/yogurt.jpg",
    sourceKeys: ["dairy"],
    sortOrder: 1,
  }),
  createSubcategory({
    id: "subcategory-breakfast-dairy",
    categoryId: "category-dairy-breakfast",
    categoryKey: "dairy-breakfast",
    key: "breakfast-dairy",
    labelBn: "ব্রেকফাস্ট ডেইরি",
    labelEn: "Breakfast Dairy",
    descriptionBn: "সকালের টেবিলের জন্য হালকা দুগ্ধজাত পছন্দ।",
    descriptionEn: "Light dairy picks for breakfast tables.",
    imageUrl: "/yogurt-2.jpg",
    sourceKeys: ["dairy"],
    sortOrder: 2,
  }),
  createSubcategory({
    id: "subcategory-family-pack-dairy",
    categoryId: "category-dairy-breakfast",
    categoryKey: "dairy-breakfast",
    key: "family-pack-dairy",
    labelBn: "ফ্যামিলি প্যাক ডেইরি",
    labelEn: "Family Pack Dairy",
    descriptionBn: "পরিবারের জন্য বড় সাইজের ডেইরি প্যাক।",
    descriptionEn: "Family-sized yogurt and dairy packs.",
    imageUrl: "/yogurt.jpg",
    sourceKeys: ["dairy"],
    sortOrder: 3,
  }),
  createSubcategory({
    id: "subcategory-probiotic-dairy",
    categoryId: "category-dairy-breakfast",
    categoryKey: "dairy-breakfast",
    key: "probiotic-dairy",
    labelBn: "প্রোবায়োটিক ডেইরি",
    labelEn: "Probiotic Dairy",
    descriptionBn: "ওয়েলনেস রুটিনের জন্য দই-ভিত্তিক পছন্দ।",
    descriptionEn: "Yogurt-based picks for wellness routines.",
    imageUrl: "/yogurt-2.jpg",
    sourceKeys: ["dairy"],
    sortOrder: 4,
  }),

  createSubcategory({
    id: "subcategory-daily-market",
    categoryId: "category-fresh-vegetables",
    categoryKey: "fresh-vegetables",
    key: "daily-market",
    labelBn: "দৈনিক বাজার",
    labelEn: "Daily Market",
    descriptionBn: "প্রতিদিনের বাজারের লাইভ তালিকা।",
    descriptionEn: "A live list of vegetables for daily cooking.",
    imageUrl: "/organic-vegetables.jpg",
    sourceKeys: ["vegetables"],
    sortOrder: 0,
  }),
  createSubcategory({
    id: "subcategory-leafy-greens",
    categoryId: "category-fresh-vegetables",
    categoryKey: "fresh-vegetables",
    key: "leafy-greens",
    labelBn: "পাতাজাত সবজি",
    labelEn: "Leafy Greens",
    descriptionBn: "ভাজি ও সালাদের জন্য পাতাজাত সবজি।",
    descriptionEn: "Leafy vegetables for bhaji and salads.",
    imageUrl: "/organic-vegetables.jpg",
    sourceKeys: ["vegetables"],
    sortOrder: 1,
  }),
  createSubcategory({
    id: "subcategory-root-vegetables",
    categoryId: "category-fresh-vegetables",
    categoryKey: "fresh-vegetables",
    key: "root-vegetables",
    labelBn: "মূলজাত সবজি",
    labelEn: "Root Vegetables",
    descriptionBn: "আলু, গাজর ও মূলজাত রান্নার উপকরণ।",
    descriptionEn: "Roots and tubers for hearty daily meals.",
    imageUrl: "/organic-vegetables.jpg",
    sourceKeys: ["vegetables"],
    sortOrder: 2,
  }),
  createSubcategory({
    id: "subcategory-cooking-vegetables",
    categoryId: "category-fresh-vegetables",
    categoryKey: "fresh-vegetables",
    key: "cooking-vegetables",
    labelBn: "রান্নার সবজি",
    labelEn: "Cooking Vegetables",
    descriptionBn: "কারি, ভর্তা এবং তরকারির জন্য।",
    descriptionEn: "Vegetable picks suited for curries and home cooking.",
    imageUrl: "/organic-vegetables.jpg",
    sourceKeys: ["vegetables"],
    sortOrder: 3,
  }),
  createSubcategory({
    id: "subcategory-salad-vegetables",
    categoryId: "category-fresh-vegetables",
    categoryKey: "fresh-vegetables",
    key: "salad-vegetables",
    labelBn: "সালাদ সবজি",
    labelEn: "Salad Vegetables",
    descriptionBn: "হালকা ও ফ্রেশ টেবিল সিলেকশন।",
    descriptionEn: "Fresh salad-friendly vegetables.",
    imageUrl: "/organic-vegetables.jpg",
    sourceKeys: ["vegetables"],
    sortOrder: 4,
  }),

  createSubcategory({
    id: "subcategory-organic-vegetables",
    categoryId: "category-organic-certified",
    categoryKey: "organic-certified",
    key: "organic-vegetables",
    labelBn: "অর্গানিক সবজি",
    labelEn: "Organic Vegetables",
    descriptionBn: "অর্গানিক এবং পরিচ্ছন্ন সবজির সংগ্রহ।",
    descriptionEn: "A clean, organic vegetables collection.",
    imageUrl: "/organic-vegetables.jpg",
    sourceKeys: ["vegetables"],
    sortOrder: 0,
  }),
  createSubcategory({
    id: "subcategory-organic-honey",
    categoryId: "category-organic-certified",
    categoryKey: "organic-certified",
    key: "organic-honey",
    labelBn: "অর্গানিক মধু",
    labelEn: "Organic Honey",
    descriptionBn: "বিশ্বাসযোগ্য অর্গানিক মধুর পছন্দ।",
    descriptionEn: "A trusted organic honey range.",
    imageUrl: "/deal-3.jpg",
    sourceKeys: ["honey"],
    sortOrder: 1,
  }),
  createSubcategory({
    id: "subcategory-organic-fruit",
    categoryId: "category-organic-certified",
    categoryKey: "organic-certified",
    key: "organic-fruit",
    labelBn: "অর্গানিক ফল",
    labelEn: "Organic Fruit",
    descriptionBn: "প্রাকৃতিকভাবে নির্বাচিত ফল।",
    descriptionEn: "Naturally selected fruit picks.",
    imageUrl: "/mango-2.jpg",
    sourceKeys: ["fruit"],
    sortOrder: 2,
  }),
  createSubcategory({
    id: "subcategory-organic-dairy",
    categoryId: "category-organic-certified",
    categoryKey: "organic-certified",
    key: "organic-dairy",
    labelBn: "অর্গানিক ডেইরি",
    labelEn: "Organic Dairy",
    descriptionBn: "স্বাস্থ্যকর দুগ্ধজাত খাবারের বিভাগ।",
    descriptionEn: "A healthier dairy-focused selection.",
    imageUrl: "/yogurt-2.jpg",
    sourceKeys: ["dairy"],
    sortOrder: 3,
  }),
  createSubcategory({
    id: "subcategory-certified-wellness",
    categoryId: "category-organic-certified",
    categoryKey: "organic-certified",
    key: "certified-wellness",
    labelBn: "সার্টিফায়েড ওয়েলনেস",
    labelEn: "Certified Wellness",
    descriptionBn: "ওয়েলনেস-ফার্স্ট প্রোডাক্ট কিউরেশন।",
    descriptionEn: "Wellness-first certified product picks.",
    imageUrl: "/tea.jpg",
    sourceKeys: ["honey", "vegetables", "fruit"],
    sortOrder: 4,
  }),

  createSubcategory({
    id: "subcategory-cooking-oils",
    categoryId: "category-kitchen-essentials",
    categoryKey: "kitchen-essentials",
    key: "cooking-oils",
    labelBn: "কুকিং অয়েল",
    labelEn: "Cooking Oils",
    descriptionBn: "রান্নাঘরের নিয়মিত তেলের বিভাগ।",
    descriptionEn: "Daily cooking oils and kitchen basics.",
    imageUrl: "/olive-oil.jpg",
    sourceKeys: ["oil"],
    sortOrder: 0,
  }),
  createSubcategory({
    id: "subcategory-pantry-ghee",
    categoryId: "category-kitchen-essentials",
    categoryKey: "kitchen-essentials",
    key: "pantry-ghee",
    labelBn: "প্যান্ট্রি ঘি",
    labelEn: "Pantry Ghee",
    descriptionBn: "রান্নার জন্য গৃহস্থালির ঘি নির্বাচন।",
    descriptionEn: "A pantry-ready ghee selection for cooking.",
    imageUrl: "/oil-2.jpg",
    sourceKeys: ["ghee"],
    sortOrder: 1,
  }),
  createSubcategory({
    id: "subcategory-natural-sweeteners",
    categoryId: "category-kitchen-essentials",
    categoryKey: "kitchen-essentials",
    key: "natural-sweeteners",
    labelBn: "ন্যাচারাল সুইটেনার",
    labelEn: "Natural Sweeteners",
    descriptionBn: "গুড়-ভিত্তিক কিচেন সুইটেনার।",
    descriptionEn: "Jaggery-led sweeteners for the kitchen.",
    imageUrl: "/fruits.jpg",
    sourceKeys: ["gur"],
    sortOrder: 2,
  }),
  createSubcategory({
    id: "subcategory-breakfast-basics",
    categoryId: "category-kitchen-essentials",
    categoryKey: "kitchen-essentials",
    key: "breakfast-basics",
    labelBn: "ব্রেকফাস্ট বেসিক",
    labelEn: "Breakfast Basics",
    descriptionBn: "সকালের টেবিলের জন্য সহজ পছন্দ।",
    descriptionEn: "Easy breakfast-ready essentials.",
    imageUrl: "/yogurt.jpg",
    sourceKeys: ["dairy", "gur"],
    sortOrder: 3,
  }),
  createSubcategory({
    id: "subcategory-family-combo",
    categoryId: "category-kitchen-essentials",
    categoryKey: "kitchen-essentials",
    key: "family-combo",
    labelBn: "ফ্যামিলি কম্বো",
    labelEn: "Family Combos",
    descriptionBn: "পরিবারভিত্তিক কিচেন প্যাক।",
    descriptionEn: "Combined staples for family kitchens.",
    imageUrl: "/special-offer.jpg",
    sourceKeys: ["oil", "ghee", "dairy", "gur"],
    sortOrder: 4,
  }),

  createSubcategory({
    id: "subcategory-immunity-boosters",
    categoryId: "category-wellness-picks",
    categoryKey: "wellness-picks",
    key: "immunity-boosters",
    labelBn: "ইমিউনিটি বুস্টার",
    labelEn: "Immunity Boosters",
    descriptionBn: "ওয়েলনেস ও ইমিউনিটির জন্য নির্বাচিত পণ্য।",
    descriptionEn: "Wellness and immunity-focused product picks.",
    imageUrl: "/tea.jpg",
    sourceKeys: ["honey", "fruit"],
    sortOrder: 0,
  }),
  createSubcategory({
    id: "subcategory-detox-green",
    categoryId: "category-wellness-picks",
    categoryKey: "wellness-picks",
    key: "detox-green",
    labelBn: "ডিটক্স গ্রিন",
    labelEn: "Detox Greens",
    descriptionBn: "সবজি ও গ্রিন-ভিত্তিক সিলেকশন।",
    descriptionEn: "Green, produce-led detox selections.",
    imageUrl: "/organic-vegetables.jpg",
    sourceKeys: ["vegetables"],
    sortOrder: 1,
  }),
  createSubcategory({
    id: "subcategory-energy-snacks",
    categoryId: "category-wellness-picks",
    categoryKey: "wellness-picks",
    key: "energy-snacks",
    labelBn: "এনার্জি স্ন্যাকস",
    labelEn: "Energy Snacks",
    descriptionBn: "দ্রুত এনার্জির জন্য ফল ও মধুর প্যাক।",
    descriptionEn: "Fruit and honey picks for quick daily energy.",
    imageUrl: "/fruits.jpg",
    sourceKeys: ["fruit", "honey"],
    sortOrder: 2,
  }),
  createSubcategory({
    id: "subcategory-seasonal-wellness",
    categoryId: "category-wellness-picks",
    categoryKey: "wellness-picks",
    key: "seasonal-wellness",
    labelBn: "সিজনাল ওয়েলনেস",
    labelEn: "Seasonal Wellness",
    descriptionBn: "ঋতুভিত্তিক স্বাস্থ্যকর পছন্দ।",
    descriptionEn: "Seasonal wellness-focused selections.",
    imageUrl: "/mango-2.jpg",
    sourceKeys: ["fruit", "honey", "vegetables"],
    sortOrder: 3,
  }),
  createSubcategory({
    id: "subcategory-herbal-picks",
    categoryId: "category-wellness-picks",
    categoryKey: "wellness-picks",
    key: "herbal-picks",
    labelBn: "হারবাল পিকস",
    labelEn: "Herbal Picks",
    descriptionBn: "প্রাকৃতিক রুটিনের হারবাল ও পিওর পছন্দ।",
    descriptionEn: "Curated pure-food picks for herbal routines.",
    imageUrl: "/tea.jpg",
    sourceKeys: ["honey", "vegetables"],
    sortOrder: 4,
  }),
];
